---
booktitle: Proceedings of the 2nd NeurIPS Workshop on Symmetry and Geometry in Neural
  Representations
shortname: NeurReps
volume: '228'
year: '2023'
start: &1 2023-12-16
end: 2023-12-16
published: 2024-08-02
layout: proceedings
series: Proceedings of Machine Learning Research
publisher: PMLR
issn: 2640-3498
id: neurreps2023
month: 0
cycles: false
bibtex_editor: Sanborn, Sophia and Shewmake, Christian and Azeglio, Simone and Miolane,
  Nina
editor:
- given: Sophia
  family: Sanborn
- given: Christian
  family: Shewmake
- given: Simone
  family: Azeglio
- given: Nina
  family: Miolane
title: Proceedings of Machine Learning Research
description: |
  Proceedings of the 2nd NeurIPS Workshop on Symmetry and Geometry in Neural Representations
    Held in New Orleans, Lousiana, USA on 16 December 2023

  Published as Volume 228 by the Proceedings of Machine Learning Research on 02 August 2024.

  Volume Edited by:
    Sophia Sanborn
    Christian Shewmake
    Simone Azeglio
    Nina Miolane

  Series Editors:
    Neil D. Lawrence
date_str: 16 Dec
url: https://proceedings.mlr.press
author:
  name: PMLR
baseurl: "/v228"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
exclude:
- README.md
- Gemfile
- ".gitignore"
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: mlresearch/jekyll-theme
style: pmlr
permalink: "/:title.html"
ghub:
  edit: true
  repository: v228
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
volume_type: Volume
volume_dir: v228
email: ''
conference:
  name: NeurIPS Workshop on Symmetry and Geometry in Neural Representations
  url: https://neurreps.org
  location: New Orleans, Lousiana, USA
  dates:
  - *1
analytics:
  google:
    tracking_id: UA-92432422-1
orig_bibfile: "/Users/neil/mlresearch/v228/neurreps2023.bib"
# Site settings
# Original source:  /Users/neil/mlresearch/v228/neurreps2023.bib
